### ISSUE TITLE
looking for a new maintainer

### ISSUE THREAD

**Issue by hunleyd** [hunleyd/btrfs-auto-snapshot#19]
this project needs a new maintainer. I no longer run BTRFS on my personal device and cannot give the sporadic issues that are filed the timeliness nor the thoroughness they deserve. Anyone want to step up?

**Comment by hunleyd** [comment]
@ttv20 or @ams-tschoening any interest?

**Comment by veda-tschoening** [comment]
> @ams-tschoening any interest?

Sorry, but no, I don't have the time as well, changed employer and my focus is development currently. Don't need to maintain any systems at all currently and btrfs-auto-snapshot simply worked good enough for me in the past anyway.

**Comment by motiejus** [comment]
I can chime in.

Background: I used `btrfs-auto-snapshot` from ~2016 until ~2023. My earliest "coded" reference is from [2022](https://github.com/motiejus/code/commits/master/ansible/roles/btrfs/files/btrfs-auto-snapshot), but I certainly used it before 2022, just without ansible. It worked perfectly.

In 2024 I had enough of zfs and am now in progress of moving all my Linux systems back to btrfs, with `btrfs-auto-snapshot /home`. Today I started creating a NixOS package when I opened issues and found this one. I will create a NixOS package regardless (and the first, and possibly only, distro-specific patch will replace `#!/bin/bash` to `#!/usr/bin/env bash`). :)

This project was and will be useful for me and requires low enough attention that I have bandwidth for.

However, to make it sustainable, I cannot promise any ETAs or timelines on when the issues would be reacted upon.

One question: would you do `logger` again, or do something akin to `>&2 echo "[LEVEL] $*"` for log statements?

**Comment by hunleyd** [comment]
> I can chime in.
> 
> Background: I used `btrfs-auto-snapshot` from ~2016 until ~2023. My earliest "coded" reference is from [2022](https://github.com/motiejus/code/commits/master/ansible/roles/btrfs/files/btrfs-auto-snapshot), but I certainly used it before 2022, just without ansible. It worked perfectly.
> 

I'm happy to hear it worked well for you!

> In 2024 I had enough of zfs and am now in progress of moving all my Linux systems back to btrfs, with `btrfs-auto-snapshot /home`. Today I started creating a NixOS package when I opened issues and found this one. I will create a NixOS package regardless (and the first, and possibly only, distro-specific patch will replace `#!/bin/bash` to `#!/usr/bin/env bash`). :)
> 

That edit should probably be done just as a matter of 'best practices'

> This project was and will be useful for me and requires low enough attention that I have bandwidth for.
> 

That's great news! Did you want me to grant you permissions here, or did you want to fork and I'll mark this as archived and point people to your fork?

> One question: would you do `logger` again, or do something akin to `>&2 echo "[LEVEL] $*"` for log statements?

I'm not sure honestly, but at first blush probably just `echo` statements with the assumption that it's running under a systemd timer and the stdout/stderr will be captured by journald.

**Comment by motiejus** [comment]
> That's great news! Did you want me to grant you permissions here, or did you want to fork and I'll mark this as archived and point people to your fork?

I wasn't sure thus omitted this part. Would you be available to review of some chore PRs (I have three small ones in mind soon: logger, shebang and a CI hook for shellcheck), or you want to get this out of your radar sooner than later? If you are fine with keeping it for a while, I guess it's slightly easier for me if it's kept under your name, and if it goes well with time, we can reconsider. But you can do a hard-break if you want, I will definitely make sure to note the origins in the README (like [this](https://github.com/uber/hermetic_cc_toolchain/?tab=readme-ov-file#project-origin)). Up to you.

> > One question: would you do `logger` again, or do something akin to `>&2 echo "[LEVEL] $*"` for log statements?
> 
> I'm not sure honestly, but at first blush probably just `echo` statements with the assumption that it's running under a systemd timer and the stdout/stderr will be captured by journald.

:+1:

**Comment by hunleyd** [comment]
I have no problems holding onto it and punting till later @motiejus . Whatever works best for you.

**Comment by hunleyd** [comment]
@motiejus let me know if I should make a release after merging your latest PR or if you have some other things you'd like to see get merged first. And thanks again for your efforts!

**Comment by motiejus** [comment]
@hunleyd I realized syslog is optional, so nothing to do there. I would appreciate a release, so it includes your latest merge w.r.t. handling of the trailing slash.

**Comment by hunleyd** [comment]
I've just released [v2.0.4](https://github.com/hunleyd/btrfs-auto-snapshot/releases/tag/v2.0.4) and invited you as a collaborator on the repo. Once you've accepted the invite, I'll bump up your perms. Thanks again for stepping in!

**Comment by motiejus** [comment]
Happy to take part!
