### ISSUE TITLE
Logger throws error on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by andreas5232** [hunleyd/btrfs-auto-snapshot#3]
When running btrfs-auto-snapshot on Ubuntu 20.04 LTS with `--syslog` option, I get the following error:

```
logger: invalid option -- 'r'
Try 'logger --help' for more information.
```

**Comment by hunleyd** [comment]
give that a whirl and  let me know if it doesn't resolve things for you.

**Comment by andreas5232** [comment]
Logging to syslog is working again now. Thank you for the quick fix! :)
